# Generated by Django 3.2.3 on 2021-06-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayarlar',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
