# Generated by Django 3.2.3 on 2021-06-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210601_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayarlar',
            options={'ordering': ['ID'], 'verbose_name': 'Ayarlar', 'verbose_name_plural': 'Ayarlar'},
        ),
    ]
