# Generated by Django 3.2.3 on 2021-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_ayarlar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriler',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Baslik', models.CharField(max_length=120, verbose_name='Kategori Başlık')),
                ('Aciklama', models.TextField(blank=True, verbose_name='Kategori Açıklama')),
            ],
            options={
                'verbose_name': 'Kategoriler',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['ID'],
            },
        ),
    ]
