# Generated by Django 3.2.3 on 2021-06-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_kategoriler'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonDakika',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Haber', models.TextField(verbose_name='Haber İçeriği')),
            ],
            options={
                'verbose_name': 'Son Dakika Haberleri',
                'verbose_name_plural': 'Son Dakika Haberleri',
                'ordering': ['ID'],
            },
        ),
    ]
