# Generated by Django 3.2.3 on 2021-06-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_sosyalmedyaikonlari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosyalmedyaikonlari',
            options={'ordering': ['ID'], 'verbose_name': 'Sosyal Medya İkon Tanımları', 'verbose_name_plural': 'Sosyal Medya İkon Tanımları'},
        ),
    ]
