# Generated by Django 3.2.3 on 2021-06-01 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_sosyalmedyaikonlari_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosyalMedyaHesaplari',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Baslik', models.CharField(max_length=120, verbose_name='Başlık')),
                ('Adres', models.CharField(max_length=500, verbose_name='URL')),
                ('IkonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.sosyalmedyaikonlari', unique=True)),
            ],
            options={
                'verbose_name': 'Sosyal Medya Hesap Tanımları',
                'verbose_name_plural': 'Sosyal Medya Hesap Tanımları',
                'ordering': ['ID'],
            },
        ),
    ]
