# Generated by Django 3.2.3 on 2021-06-02 05:29

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_sosyalmedyahesaplari_ikonid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haberler',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Baslik', models.CharField(max_length=120, verbose_name='Haber Başlık')),
                ('Aciklama', models.TextField(blank=True, verbose_name='Haber Açıklama')),
                ('Icerik', djrichtextfield.models.RichTextField()),
                ('Resim', models.ImageField(blank=True, null=True, upload_to='news')),
                ('SliderAlani', models.BooleanField(verbose_name='Slider Alanında Gözüksün mü?')),
                ('YayinlanmaTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('KategoriID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.kategoriler')),
            ],
            options={
                'verbose_name': 'Haberler',
                'verbose_name_plural': 'Haberler',
                'ordering': ['ID'],
            },
        ),
    ]
