# Generated by Django 3.2.3 on 2021-06-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_haberler_kategoriid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haberler',
        ),
    ]
