# Generated by Django 3.2.3 on 2021-06-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_haberler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haberler',
            name='KategoriID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.kategoriler'),
        ),
    ]
