# Generated by Django 3.2.3 on 2021-06-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_haberler_kategoriid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='SiteBanner',
            field=models.ImageField(blank=True, null=True, upload_to='core'),
        ),
    ]
