# Generated by Django 3.2.3 on 2021-06-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_ayarlar_sitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='SiteCopyright',
            field=models.CharField(default='Copyright ©', max_length=300, verbose_name='Site Altında Gözüken Copyright Yazısı'),
        ),
    ]
